#!/usr/bin/env bash
Modèle conceptuel qui caractérise les fonctions de communication d'un système de télécommunication sans prendre en compte sa structure interne et sa technologie sous-jacente
Du niveau le plus bas au niveau le plus élevé
