#!/usr/bin/env bash
# Vérifie si un argument est passé
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Envoie un ping à l'adresse IP spécifiée
ping -c 5 "$1"
